### ISSUE TITLE
Error if historical_ts_categorical is empty

### ISSUE THREAD

**Issue by giadasp** [PlaytikaResearch/tft-torch#5]
My dataset has no historical categorical variables.

When I run the code for training in your docs https://playtikaresearch.github.io/tft-torch/build/html/tutorials/TrainingExample.html with my data I get the following error:

`x_reshape = x.contiguous().view(-1, x.size(-1))  # (samples * time-steps, input_size)
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension 
size -1 can be any value and is ambiguous`

How can I overcome this issue?

**Comment by Dvirbeno** [comment]
Thanks @giadasp for pointing this out.

I fixed the specified behavior in #6.
Please update if your issue is resolved after these changes.

**Comment by giadasp** [comment]
Lovely!
